# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
type: application
name: cluster-aks
description: A Helm chart for creating Cluster API clusters with the Azure infrastructure provider (CAPZ) in AKS mode.
appVersion: 0.0.1
version: 0.2.0
home: https://github.com/giantswarm/cluster-aks
icon: https://s.giantswarm.io/app-icons/azure/1/light.svg
sources:
  - https://github.com/giantswarm/cluster-aks
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "false"
dependencies:
  - name: cluster
    version: "6.7.0"
    repository: https://giantswarm.github.io/cluster-catalog
