{{- define "AKSCertManagerCrossplaneResourcesHelmValues" }}
providers:
  azure:
    subscriptionId: {{ .Values.global.providerSpecific.subscriptionId }}
    location: {{ .Values.global.providerSpecific.location }}
{{- end }}
