{{/* AKS-specific external-dns Helm values*/}}
{{/* https://github.com/giantswarm/external-dns-app/blob/main/helm/external-dns-app/values.yaml*/}}
{{- define "AKSExternalDnsHelmValues" }}
provider: azure
clusterID: {{ include "cluster-aks.resource.name" $ }}
domainFilters:
  - "{{ .Values.global.connectivity.baseDomain }}"
txtOwnerId: giantswarm-io-external-dns
txtPrefix: {{ include "cluster-aks.resource.name" $ }}
{{- end }}
